repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        exclude: data_analysis/externals
        args: ['--ignore=E203, E722,W503,W504']
