version: 0.0.1

calibration:
  pupil_detection: PL
  eye: binocular
  algorithm: 2D-PL

visualization:
  start_time: 
    - 0
    - 30
  end_time: 
    - 1
    - 0
  run_for_all_frames: True
  use_vedb_gaze_pipeline: False
  pupil_labs_output_id: 0
  save_world_output: True
  save_eye_output: True
  world_scale: 0.5
  eye_scale: 0.5
  eye_fps_scale: 4
  marker_size: 4
  marker_color: cyan
  eye_index : binocular


directory:
  session_directory: "/hdd01/kamran_sync/staging/"
  gaze_directory:  "/hdd01/kamran_sync/processed/gaze_pilot/"
  saving_directory: "/hdd01/kamran_sync/processed/visualization/"
  cumulative_gaze_file: "/home/kamran/Desktop/gaze_accuracy.npz"
